### ISSUE TITLE
add 2023 workshops

### ISSUE THREAD

**Issue by bbest** [cstories-app/cstories-app.github.io#10]
From Grace:

Could one of you please update the Workshops page of [cstories.app](http://cstories.app/)? We’ll want to add the following:

Date | Event   | Host
-----|--------|----- 
February 2, 2023 | Workshop `#3` at RCAA*  | Redwood Community Action Agency
February 8, 2023 | Workshop `#4` at SBMM** | Santa Barbara Maritime Museum

Please add button to RSVP for each of the events:

- \* RCAA: https://forms.gle/Wuvb6GdGZScFouFp9
- \*\*  SBMM: https://forms.gle/wJRJgEqJX4YSCpAJ9

Tasks:
- [x] Create a linked page with details for Workshop `#3`. Please mirror the details from Workshop `#2` except change the date to 2023-02-02 and remove the Quick Links for now
- [x] Create a linked page with details for Workshop `#4`. Mirror the details from Workshop `#1` except chnge the date to 2023-02-08 and remove the Quick Links for now.

Please complete by the end of this year. We’ll want to start sending out invitations to community members in early January 2023.

**Comment by bbest** [comment]
Hi @jzadra, 

Thanks for jumping on this. Please let me know if you have any trouble implementing. 

You'll want to create new Quarto documents (*.qmd) in [`workshops/`](https://github.com/cstories-app/cstories-app.github.io/tree/main/workshops). The index.qmd and workshops.qmd then slurp the metadata from the YAML frontmatter of those to populate in the [listings](https://quarto.org/docs/websites/website-listings.html).

**Comment by jzadra** [comment]
The RSVP links are bad - they go to a form that is closed and no longer accepting responses. Grace has been notified.
