### ISSUE TITLE
update basemap from defunct Esri.OceanBasemap in infographics/viewshed

### ISSUE THREAD

**Issue by bbest** [cstories-app/cstories-app.github.io#12]
@jzadra has used MapBox ocean basemaps with rstudio/leaflet

**Comment by jzadra** [comment]
We need a method to safely store credentials for MapBox API, @bbest do you already have a solution to this for a quarto site?

**Comment by bbest** [comment]
Hi @jzadra,

There are many ways of approaching this, but the most important thing is not putting the password file in the Github repo for public viewing. If you put it in your user folder, then we @geocoug and I can copy it into our system, e.g.:

```r
mb_key <- readLines("~/.mapbox_key_jzadra.txt")
```

The `.` prefix hides it from typically directory listing.

**Comment by jzadra** [comment]
In this case it needs to be in able to grab the tiles from the API each time it runs, but I think I have it figured out.

**Comment by jzadra** [comment]
I'm not finding a tileset from MapBox that is analogous to the current esri basemap.  What is the issue with the esri tile set?

Current map:

![image](https://user-images.githubusercontent.com/25590353/210437410-2c5ffd8f-4322-4fb8-8d2f-a85244bc89b0.png)


Mapbox Options:

![image](https://user-images.githubusercontent.com/25590353/210437492-495e2446-0025-4b43-b6d4-8bae33a71925.png)

![image](https://user-images.githubusercontent.com/25590353/210437625-5cd5fd30-2ad5-47cb-be9d-ced01b3d4c02.png)

**Comment by bbest** [comment]
Hi @jzadra, 

You're showing the previously rendered Ocean Basemap, but now here's what I see from Google Chrome browser:

- https://cstories.app/infographics/viewshed.html
  <img width="819" alt="image" src="https://user-images.githubusercontent.com/2837257/210553370-4023f4b1-163f-41f7-9b57-8943b3959264.png">

This map is using the `Esri.OceanBasemap` per:

https://github.com/cstories-app/cstories-app.github.io/blob/87717709224c37c50e11d3deddac2cbb1e30e65b/infographics/viewshed.qmd#L37

But the problem is that basemap got deprecated, i.e. retired, per:

- [Notification That a Legacy Ocean Basemap Will Be Retired December 1, 2022](https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/announcements/notification-that-a-legacy-ocean-basemap-will-be-retired-in-2022/)

**Comment by bbest** [comment]
For now, I applied a different working basemap that has shaded relief ocean bathymetry:

[Esri.OceanBasemap -> Esri.NatGeoWorldMap](https://github.com/cstories-app/cstories-app.github.io/commit/d52a861c6e212bc31f12da77d3c91dd0fd728e25)

<img width="818" alt="image" src="https://user-images.githubusercontent.com/2837257/210554580-df822d8c-a406-4de3-b86a-64595a7233a6.png">
