### ISSUE TITLE
infographiq.js fixes

### ISSUE THREAD

**Issue by bbest** [cstories-app/cstories-app.github.io#2]
https://cstories.app/infographics/info1.html

![Image](https://user-images.githubusercontent.com/2837257/200949625-10c23b6e-a508-4c36-ac14-a8838c9a0fa1.png)

Deal with a bunch of issues:

- [x] labels on hover way off
- [x] missing yellow highlight of icon
- [ ] ...

Wishlist (later):

- [ ] make icons selectable within entire convex hull of points, a la [observablehq.com/@d3/d3-polygonhull](https://observablehq.com/@d3/d3-polygonhull) (old [`d3.geom.hull()`](https://d3-wiki.readthedocs.io/zh_CN/master/Hull-Geom/) for new [`d3.polygonHull(points) `](https://github.com/d3/d3-polygon/blob/main/README.md#polygonHull))

## References

See: [README - infographics - Google Docs](https://docs.google.com/document/d/1WR7WSV3VOo771ufS0nPUhsrTJ2jXV2HRpH9l7H9n2nI/edit#)

**Comment by bbest** [comment]
http://localhost:4489/infographics/info1.html

![Image](https://user-images.githubusercontent.com/2837257/200949625-10c23b6e-a508-4c36-ac14-a8838c9a0fa1.png)

Deal with a bunch of issues:

- [ ] labels on hover way off
- [ ] missing yellow highlight of icon
- [ ] ...

**Comment by geocoug** [comment]
Clear modal content on modal close in infographiq.js. Currently, modal content is only overwritten when another SVG icon is clicked causing content from the previously clicked icon to appear in the modal before showing new content.

**Comment by bbest** [comment]
Minor notes:

- Have to manually copy edited *.svg files into the _site/* folder.
- Thickness of yellow hover is a bit different b/n icons.
